### ISSUE TITLE
Project setup and initail development (Team work) - [3H]

### ISSUE THREAD

**Issue by zainabbehzad** [zainabbehzad/space-travelers-hub#1]
1: Setup repository on Gethub 
2:Create and structure the initial React app
3:Install necessary dependencies (React Redux, Redux Logger, React Router)
4:Create initial routes and basic components (Rockets, Missions, My Profile, Dragons)
5:Download and add the app logo

**Comment by ahzamir** [comment]
@faridafaqiri 
@Fikrat2002 
@zainabbehzad 

- Well done team your project Kanban board have been approved and you can start working on it
