### ISSUE TITLE
Data fetching & State Management  (Team work)  - [10H]

### ISSUE THREAD

**Issue by zainabbehzad** [zainabbehzad/space-travelers-hub#2]
1: Fetch data from SpaceX API for Rockets, Missions, Dragons
2: Dispatch actions to store fetched data in Redux
3: Create selectors to retrieve state slices

**Comment by ahzamir** [comment]
Hey @zainabbehzad  This task should be done individually not as a group, for example my part is to work on the mission I am responsible to fetch the missions data from API and add its state to the redux store and then add some actions and reducer to update the state on redux store while user joined a mission these all belong to me and the other person is responsible for the Rockets and Drgons.

- Separate this task in to 3 tasks and assign them to the responsible persons

**Comment by zainabbehzad** [comment]
@ahzamir 
Hello Sir!
Hope you doing well.
Sir sorry as I had already added this task individually for each members, just I added it here because of Draogons section as this section is teamwork.
Now what should  we do sir should we delete it or keep it?
